### PR TITLE
migrate to new platform infrastructure rest api, travis and remove circle (THIS IS NEEDED FOR 19.02)

### PR DESCRIPTION
**Pull request by mkarmona**
1. enable new way to proxy through API
2. enable travis build
3. remove circle ci integration

### CODE REVIEW

**Comment by opentargets-fern** [comment]
Deploy preview for *paratrooper-antelope-70721* ready!

Built with commit 91d8558c9129efafbcdfb593861496020082344c

https://deploy-preview-297--paratrooper-antelope-70721.netlify.com

**Comment by LucaFumis** [comment]
Hi @mkarmona, as per chat I've been looking into this and why the preview in netlify (to test the redirects) returns 404.
It seems that commit 3b8783a breaks it: there the build scripts in package.json change, and `gulp build-all` is not called, leaving the build without an index.html page.
I'll try reverting that and see if the problem persists.

**Comment by LucaFumis** [comment]
With the last commit and a clean build, it now seems to work OK. @mkarmona we can discuss tomorrow.

**Comment by mkarmona** [comment]
thanks @LucaFumis .The commit you did duplicate the command and you are
probably breaking the travis. I will have a look either tonight or tomorrow
best!

Saludos,
Miguel Carmona
PGP PUBLIC KEY
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0x12959B27D96C797D>

**Comment by LucaFumis** [comment]
Had a chat with @mkarmona and it seems it all works OK, so it's good to merge.
If there are any issues on the Travis side (it is possible the `gulp build-all` part is being called twice) we'll look at those separately with @mkarmona.

**Pull request merged**
