### PR TITLE
Added separate markdown API documentation

### PR DESCRIPTION
**Pull request by LucaFumis**

### CODE REVIEW

**Comment by opentargets-fern** [comment]
Deploy preview ready!

Built with commit 41beecee28d7bd56854a4bcbde635e21edbca251

https://deploy-preview-151--paratrooper-antelope-70721.netlify.com

**Comment by elipapa** [comment]
👍  great thanks. I'll add a commit to point to the new API on appengine. I want to take the top portion away from the swagger.yaml there.

**Comment by apierleoni** [comment]
@elipapa 
not sure it is a good idea to take that portion away. it currently lives with the api, it is parsed by the client, and it allows us to make sure that the doc is in sync with the api.
any good reason, apart the google endpoint page looking terrible?
not sure of what is the plan here, but moving the api docs to the webapp is a big NO GO for me.
are you splitting the docs into an other md in the api that the webapp reads?

**Comment by elipapa** [comment]
@andreap I agree 100%. The documentation should stay with API. 
As you suggested, I want to split the docs into an other `.md` in the api repo that the webapp reads.

In my mind the webapp shouldn't have to deal with the documentation anyways.. (something like this https://opentargets.gitbooks.io/faq/content/ sitting at docs.targetvalidation.org would work better imho, but that's another story). 

My reasons for this change now are:
- every change to the swagger (including fixing typos in the documentation) will now trigger an automatic _cloud endpoints_ deployment on push. It is safer to limit re-deployments to when we actually change endpoints.
- it makes it easier to keep the swagger compatible with the OpenApi specs, which are [getting stricter](https://swagger.io/specification/) and don't specifically allow for _markdown_. 
- in fact, they encourage to point to a separate place for extended documentation: https://swagger.io/specification/#externalDocumentationObject
- 😄 the google endpoint page will look better

**Comment by opentargets-fern** [comment]
it is fine to split it to an other md, but we need to change the rest api container that already support serving the documentation at /api-docs.


showing the documentation in the web app make it easier to find it

**Comment by elipapa** [comment]
👍 merging this will be dependent on the rest_api change.

**Comment by elipapa** [comment]
@apierleoni changed it so that documentation resides in the API now. 
Can you approve + merge please?

**Pull request merged**
