### PR TITLE
Adding build steps to Dockerfile; adding option to add custom .css styling

### PR DESCRIPTION
**Pull request by pieterlukasse**
This PR changes the Dockerfile into a multi-stage dockerfile to be able to build using specific node version, before adding the build result to the /var/www folder used by nginx.

Contents:
- added build steps to Dockerfile
- included an option to overwrite some runtime .css styling, where a custom .css file is taken and appended to the full .css produced by the build step file
- updated documentation (mainly parts regarding docker options)

### CODE REVIEW

**Comment by opentargets-fern** [comment]
Deploy preview for *paratrooper-antelope-70721* ready!

Built with commit 34f66d7383e6e4459280826133269d440fc3d5f4

https://deploy-preview-303--paratrooper-antelope-70721.netlify.com

**Comment by pieterlukasse** [comment]
notify: @afaulconbridge , @mkarmona , @LucaFumis

**Comment by afaulconbridge** [comment]
Did you intend to include a root `Dockerfile` or not? I see it is both in .dockerignore and committed as a file - it should be either one or the other.

**Comment by pieterlukasse** [comment]
hi @afaulconbridge, the idea of adding it to .dockerignore is so that small changes to the Dockerfile won't trigger the build process to start from line 15 again (https://github.com/opentargets/webapp/pull/303/files#diff-3254677a7917c6c01f55212f86c57fbfR15), but instead use the cached layers as much as possible. This should speed it up during development.

**Comment by pieterlukasse** [comment]
:tada:

**Pull request merged**
