### PR TITLE
Making private data sources visible in associations page + adding private data sources to the heatmap

### PR DESCRIPTION
**Pull request by pieterlukasse**
Solution for https://github.com/opentargets/platform/issues/566. This PR adds:
- new auto-expansion feature for heatmap in associations page if datatype is configured to auto-expand. This helps making a specific custom/private data sources more visible to users when they land on this page.
- new config for custom styling of datasource checkboxes .  This new option allows adding a custom style for data sources that we want to be highlighted in the associations page. This helps making a specific custom/private data source more visible to users when they land on this page. 

Below is a quick impression of the working feature:

image

### CODE REVIEW

**Comment by opentargets-fern** [comment]
Deploy preview for *paratrooper-antelope-70721* ready!

Built with commit edd4e8d7c1ba0f798cb20a54306849df25edb666

https://deploy-preview-306--paratrooper-antelope-70721.netlify.com

**Comment by pieterlukasse** [comment]
notify @LucaFumis @afaulconbridge

**Comment by LucaFumis** [comment]
Hi @pieterlukasse, thank you for this solution.
I looked at the code and tried it locally and worked fine. It wouldn't work when enabled for genetic associations, but I think it was to do with my configuration.
It also works fine when the feature is disabled (which will be our case for the moment).

@andrewhercules had some thoughts from a UX perspective - I'll wait for his feedback to see if it's something you want/need to take into account and otherwise will be OK to merge.

**Comment by pieterlukasse** [comment]
hi @LucaFumis, nice catch! I pushed up the fix as you suggested (see last commit).

**Comment by pieterlukasse** [comment]
@LucaFumis @andrewhercules I pushed up a fix for the bug @LucaFumis identified. I also replied to the comments @andrewhercules made on the issue. Are there any remaining parts that you think should be changed in this PR? Or are you OK with merging it as it is now?

**Pull request merged**
